---
# This playbook contains common plays that will be run on all nodes.

# - name: Dump all vars
#   template: src=dumpall.j2 dest=$opt_tmp/ansible.all

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: debian.yml
  when: ansible_distribution == 'Debian'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
