---
# Handler to handle common notifications. Handlers are called by other plays.
# # See http://ansible.cc/docs/playbooks.html for more information about
# handlers.
#
- name: restart shorewall
  service: name=shorewall state=restarted

- name: restart ulogd
  service: name=ulogd state=restarted

- name: restart sshd
  service: name=sshd state=restarted

